# Generated by Django 2.1.2 on 2018-12-05 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('region', models.CharField(choices=[('estado_1', 'I Tarapaca'), ('estado_2', 'II Antofagasta'), ('estado_3', 'III Atacama'), ('estado_4', 'IV Coquimbo'), ('estado_5', 'V Valparaiso'), ('estado_6', 'VI Ohiggins'), ('estado_7', 'VII Maule'), ('estado_8', 'VIII Bio Bio'), ('estado_9', 'IX Araucania'), ('estado_10', 'X Los Lagos'), ('estado_11', 'XI Aisen'), ('estado_12', 'XII Magallanes y Antartica'), ('estado_13', 'XII Metropolitana'), ('estado_14', 'IVX Los Rios'), ('estado_15', 'XV Arica y Parinacota')], default='region', max_length=25)),
                ('ciudad', models.CharField(choices=[('1', 'Arica'), ('2', 'Alto Hospicio'), ('3', 'Iquique'), ('4', 'Pozo Almonte'), ('5', 'Caldera'), ('6', 'Chanaral'), ('7', 'Copiapo'), ('8', 'Diego de Almagro'), ('9', 'El Salvador    Huasco'), ('10', 'Tierra Amarilla'), ('11', 'Vallenar'), ('12', 'Andacollo'), ('13', 'Combarbala'), ('14', 'Coquimbo'), ('15', 'El Palqui'), ('16', 'Illapel'), ('17', 'La Serena'), ('18', 'Los Vilos'), ('19', 'Montepatria'), ('20', 'Ovalle'), ('21', 'Salamanca'), ('22', 'Vicuna'), ('23', 'Algarrobo'), ('24', 'Cabildo'), ('25', 'Calle Larga'), ('26', 'Cartagena'), ('27', 'Quilpue'), ('28', 'Valparaiso'), ('29', 'Villa Alemana')], default='ciudad', max_length=25)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('encargado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('sucursal', models.TextField()),
            ],
        ),
    ]
