# Generated by Django 2.1.2 on 2018-12-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181204_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('tipo_producto', models.CharField(max_length=50)),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventas', models.TextField()),
                ('sucursal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tienda')),
            ],
        ),
        migrations.RemoveField(
            model_name='venta',
            name='nombre_producto',
        ),
        migrations.AlterField(
            model_name='venta',
            name='sucursal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tienda'),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Producto'),
        ),
    ]
