# Generated by Django 2.1.2 on 2018-12-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181206_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='sucursal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='sucursal',
            field=models.TextField(),
        ),
    ]
