# Generated by Django 2.1.2 on 2018-12-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181207_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tienda'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='sucursal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tienda'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='ventas',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='sucursal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tienda'),
        ),
    ]
