# Generated by Django 2.1.2 on 2018-12-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_producto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_oferta', models.IntegerField()),
                ('producto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Producto')),
            ],
        ),
    ]
