# Generated by Django 2.1.2 on 2018-12-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
