# Generated by Django 2.1.2 on 2018-12-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181209_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='precio_oferta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='oferta',
            field=models.BooleanField(),
        ),
    ]
