# Generated by Django 2.1.2 on 2018-12-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181209_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='precio_oferta',
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
