# Generated by Django 2.1.2 on 2018-12-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181209_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('0', 'Seleccione un tipo...'), ('1', 'Televisor'), ('2', 'Smartphone'), ('3', 'Notebook'), ('4', 'Audio'), ('5', 'Audífonos'), ('6', 'Reproductor DVD/Blu-Ray'), ('7', 'Consola de videojuegos'), ('8', 'Monitor'), ('9', 'Accesorios de computador'), ('10', 'Cámara')], default='Seleccione un tipo...', max_length=25),
        ),
    ]
