# Generated by Django 2.1.2 on 2018-12-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181209_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_desc',
            field=models.IntegerField(blank=True),
        ),
    ]
