# Generated by Django 2.1.2 on 2018-12-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_vendedor_usuariovendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='usuarioVendedor',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
